export const LOADING = 'LOADING'

export const SET_UPLOAD_FILES = 'SET_UPLOAD_FILES'
export const UPLOAD_BEGIN = 'UPLOAD_BEGIN'
export const UPLOAD_FAILED = 'UPLOAD_FAILED'
export const UPLOAD_DONE = 'UPLOAD_DONE'

export const SET_UPDATE_FILES = 'SET_UPDATE_FILES'
export const UPDATE_BEGIN = 'UPDATE_BEGIN'
export const UPDATE_DONE = 'UPDATE_DONE'
export const UPDATE_FAILED = 'UPDATE_FAILED'

export const SET_DOWNLOAD_FILES = 'SET_DOWNLOAD_FILES'
export const DOWNLOAD_FAILED = 'DOWNLOAD_FAILED'
export const DOWNLOAD_BEGIN = 'DOWNLOAD_BEGIN'
export const DOWNLOAD_DONE = 'DOWNLOAD_DONE'
export const DELETE_FILE = 'DELETE_FILE'

// Home Reducer
export const SET_SELECTED_FILE = 'SET_SELECTED_FILE'
export const SET_FILE_LIST = 'SET_FILE_LIST'
export const SET_CURRENT_FOLDER = 'SET_CURRENT_FOLDER'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const START_LOADING = 'START_LOADING'
export const DONE_LOADING = 'DONE_LOADING'
export const SET_VIEW_MODE_GRID = 'SET_VIEW_MODE_GRID'
export const SET_VIEW_MODE_LIST = 'SET_VIEW_MODE_LIST'
export const INSERT_FILES = 'INSERT_FILES'

// Modal
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
